### ISSUE TITLE
Zenroom Crash with Keypairoom

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/client_zencode#1]
When replying with **a** to the first 3 questions, this happens: 

https://gyazo.com/5014b2fa28ea6d6000f1a3453d883b6b

Zenroom's error: 

`{"result":"","logs":"[ \"ZENROOM JSON LOG START\",\n\" . Release version: v4.12.0\",\n\" . Build commit hash: 52721c9a\",\n\" . Memory manager: mimalloc\",\n\" . ECDH curve is SECP256K1\",\n\" . ECP curve is BLS381\",\n\"[W] Zencode is missing version check, please add: rule check version N.N.N\",\n\"J64 HEAP: eyJDQUNIRSI6W10sIkNPREVDIjp7Im5hbWVGaXJzdFBldCI6eyJiaW50eXBlIjoiemVucm9vbS5vY3RldCIsImVuY29kaW5nIjoic3RyaW5nIiwibmFtZSI6Im5hbWVGaXJzdFBldCIsInJvb3QiOiJ1c2VyQ2hhbGxlbmdlcyIsInplbnR5cGUiOiJlIn0sIm5hbWVGaXJzdFRlYWNoZXIiOnsiYmludHlwZSI6InplbnJvb20ub2N0ZXQiLCJlbmNvZGluZyI6InN0cmluZyIsIm5hbWUiOiJuYW1lRmlyc3RUZWFjaGVyIiwicm9vdCI6InVzZXJDaGFsbGVuZ2VzIiwiemVudHlwZSI6ImUifSwidXNlckNoYWxsZW5nZXMiOnsiZW5jb2RpbmciOiJzdHJpbmciLCJuYW1lIjoidXNlckNoYWxsZW5nZXMiLCJ6ZW50eXBlIjoiZCJ9LCJ3aGVyZUhvbWVUb3duIjp7ImJpbnR5cGUiOiJ6ZW5yb29tLm9jdGV0IiwiZW5jb2RpbmciOiJzdHJpbmciLCJuYW1lIjoid2hlcmVIb21lVG93biIsInJvb3QiOiJ1c2VyQ2hhbGxlbmdlcyIsInplbnR5cGUiOiJlIn0sIndoZXJlUGFyZW50c01ldCI6eyJiaW50eXBlIjoiemVucm9vbS5vY3RldCIsImVuY29kaW5nIjoic3RyaW5nIiwibmFtZSI6IndoZXJlUGFyZW50c01ldCIsInJvb3QiOiJ1c2VyQ2hhbGxlbmdlcyIsInplbnR5cGUiOiJlIn19LCJHSVZFTl9kYXRhIjp7InNlZWRTZXJ2ZXJTaWRlU2hhcmQuSE1BQyI6IjFBQnBhVkZTNjBNY3Z4MTJ2NHE3QnJ3UTFVK3ppSnVXMFRFeWpzNy9mU1E9IiwidXNlckNoYWxsZW5nZXMiOnsibmFtZUZpcnN0UGV0IjoiYSIsIm5hbWVGaXJzdFRlYWNoZXIiOiJhIiwibmFtZU1vdGhlck1haWQiOiIiLCJ3aGVyZUhvbWVUb3duIjoiYSIsIndoZXJlUGFyZW50c01ldCI6ImEifSwidXNlcm5hbWUiOiJpbmZvQGZvcmtib21iLmV1In0sIlRIRU4iOltdLCJXSEVOIjp7Im5hbWVGaXJzdFBldCI6IllRPT0iLCJuYW1lRmlyc3RUZWFjaGVyIjoiWVE9PSIsInVzZXJDaGFsbGVuZ2VzIjp7Im5hbWVGaXJzdFBldCI6IllRPT0iLCJuYW1lRmlyc3RUZWFjaGVyIjoiWVE9PSIsIndoZXJlSG9tZVRvd24iOiJZUT09Iiwid2hlcmVQYXJlbnRzTWV0IjoiWVE9PSJ9LCJ3aGVyZUhvbWVUb3duIjoiWVE9PSIsIndoZXJlUGFyZW50c01ldCI6IllRPT0ifX0=\",\n\"J64 TRACE: WyIrMjUgIEdpdmVuIG15IG5hbWUgaXMgaW4gYSAnc3RyaW5nJyBuYW1lZCAndXNlcm5hbWUnIiwiKzMyICBHaXZlbiBJIGhhdmUgYSAnc3RyaW5nIGRpY3Rpb25hcnknIG5hbWVkICd1c2VyQ2hhbGxlbmdlcyciLCIrMzYgIEdpdmVuIEkgaGF2ZSBhICdzdHJpbmcnIG5hbWVkICd3aGVyZVBhcmVudHNNZXQnIGluICd1c2VyQ2hhbGxlbmdlcyciLCIrMzcgIEdpdmVuIEkgaGF2ZSBhICdzdHJpbmcnIG5hbWVkICduYW1lRmlyc3RQZXQnIGluICd1c2VyQ2hhbGxlbmdlcyciLCIrMzggIEdpdmVuIEkgaGF2ZSBhICdzdHJpbmcnIG5hbWVkICd3aGVyZUhvbWVUb3duJyBpbiAndXNlckNoYWxsZW5nZXMnIiwiKzM5ICBHaXZlbiBJIGhhdmUgYSAnc3RyaW5nJyBuYW1lZCAnbmFtZUZpcnN0VGVhY2hlcicgaW4gJ3VzZXJDaGFsbGVuZ2VzJyIsIis0MCAgR2l2ZW4gSSBoYXZlIGEgJ3N0cmluZycgbmFtZWQgJ25hbWVNb3RoZXJNYWlkJyBpbiAndXNlckNoYWxsZW5nZXMnIiwiWyFdIEVycm9yIGF0IFplbmNvZGUgbGluZSA0MCIsIlshXSAvemVuY29kZV9naXZlbi5sdWE6MzUzOiBGb3VuZCBlbXB0eSBzdHJpbmcgJ25hbWVNb3RoZXJNYWlkJyBpbnNpZGUgJ3VzZXJDaGFsbGVuZ2VzJyJd\",\n\"[!] Zencode runtime error\",\n\"[!] /zencode.lua:646: Zencode line 40: Given I have a 'string' named 'nameMotherMaid' in 'userChallenges'\",\n\"[!] Execution aborted with errors.\",\n\"[*] Zenroom teardown.\",\n\" . Memory used: 596 KB\",\n\"ZENROOM JSON LOG END\" ]\n"}

`

**Comment by matteo-cristino** [comment]
The problem is not on the string "a", but the question left empy that are filled with an empty string that zenroom does not recognise as valid. This was always like this, thus it is something that was modified in the contract itself or the frontend. Tomorrow I will investigate these possibile causes

**Comment by matteo-cristino** [comment]
moved here https://github.com/dyne/starters/issues/302
